# Generated by Django 3.2 on 2021-06-08 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210607_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='prod',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
