# Generated by Django 3.2 on 2021-06-08 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_cart_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='prod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
